---
- hosts: all
  ignore_errors: yes
  tasks:
    - name: Download the file http://textfiles.com/100/914bbs.txt and save it as test.txt (hwreport.empty on the exam)
      get_url:
        url: http://textfiles.com/100/914bbs.txt
        dest: /root/test.txt
    - name: download url as hwreport.empty and rename it to hwreport
      copy:
        src: /home/ansible/hardware_reporting/hwreport.empty
        dest: /root/hwreport.txt
    - name: replace contents in hwreport.txt
      replace:
        regexp: "{{ item.src }}"
        replace: "{{ item.dest }}"
        dest: /root/hwreport.txt
      loop:
        - src: INVENTORY_HOSTNAME
          dest: "INVENTORY_HOSTNAME={{ ansible_hostname }}"
        - src: TOTAL_MEMORY
          dest: "TOTAL_MEMORY={{ ansible_memtotal_mb }}"
        - src: BIOS_VERSION
          dest: "BIOS_VERSION={{ ansible_bios_version }}" 
        - src: CPU
          dest: "CPU={{ ansible_processor }}"
        - src: DISK_SIZE_SDA
          dest: "{{ ansible_devices.sda.size | default('NONE') }}"
        - src: DISK_SIZE_SDB
          dest: "DISK_SIZE_SDB= {{ ansible_devices.sdb.size | default('NONE') }}"
        - src: DISK_SIZE_SDC
          dest: "DISK_SIZE_SDC= {{ ansible_devices.sdc.size | default('NONE') }}"
        - src: DISK_SIZE_SDD
          dest: "DISK_SIZE_SDD= {{ ansible_devices.sdd.size | default('NONE') }}"
        - src: DISK_SIZE_SDE
          dest: "DISK_SIZE_SDE= {{ ansible_devices.sde.size | default('NONE') }}"
        - src: DISK_SIZE_SDF
          dest: "DISK_SIZE_SDF= {{ ansible_devices.sdf.size | default('NONE') }}"
