---
- hosts: all
  ignore_errors: yes
  tasks:
    - name: Copy hwreport.empty to managed nodes and rename to hwreport.txt
      copy:
        src: /home/ansible/hardware_reporting/hwreport.empty
        dest: /root/hwreport.txt

    - name: replace contents in hwreport.txt
      template:
        src: hwreport.j2
        dest: /root/hwreport.txt
